use super::registry::ToolRegistry;
use super::tool::{ToolError, ToolResult};
use crate::security::{PolicyDecision, PolicyEngine};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PlanStep {
    pub tool_id: String,
    pub params: Value,
    pub description: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "status")]
pub enum PlanStepOutcome {
    Success { message: String, data: Option<Value> },
    NeedsConfirmation { explanation: crate::security::policy::ConfirmationExplanation },
    Conflict { reason: String, destination: String },
    Failed { error: String },
    Cancelled,
    Skipped,
}

#[derive(Debug, Clone, Serialize)]
pub struct PlanReport {
    pub plan_id: String,
    pub total_steps: usize,
    pub completed_steps: usize,
    pub outcomes: Vec<PlanStepOutcome>,
    pub stopped_early: bool,
    pub summary: String,
}

/// A live handle the frontend can use to request cancellation of an
/// in-flight plan. Kept in a registry keyed by plan_id so "Cancel"/"Stop"/
/// "Abort" from voice or the UI can reach whichever plan is currently running.
#[derive(Clone)]
pub struct CancellationToken(Arc<AtomicBool>);
impl CancellationToken {
    pub fn new() -> Self { CancellationToken(Arc::new(AtomicBool::new(false))) }
    pub fn cancel(&self) { self.0.store(true, Ordering::SeqCst); }
    pub fn is_cancelled(&self) -> bool { self.0.load(Ordering::SeqCst) }
}

pub struct PlanRegistry {
    tokens: Mutex<HashMap<String, CancellationToken>>,
}
impl PlanRegistry {
    pub fn new() -> Self { PlanRegistry { tokens: Mutex::new(HashMap::new()) } }
    pub fn register(&self, plan_id: &str) -> CancellationToken {
        let token = CancellationToken::new();
        self.tokens.lock().unwrap().insert(plan_id.to_string(), token.clone());
        token
    }
    pub fn cancel(&self, plan_id: &str) -> bool {
        if let Some(t) = self.tokens.lock().unwrap().get(plan_id) {
            t.cancel();
            true
        } else {
            false
        }
    }
    pub fn cleanup(&self, plan_id: &str) {
        self.tokens.lock().unwrap().remove(plan_id);
    }
}

/// Executes a plan step-by-step, stopping at the first step that needs
/// confirmation, hits a conflict, or fails — never blindly continuing past
/// any of those, per spec. Every step still goes through the PolicyEngine
/// individually; the planner does not grant itself authority to skip it.
pub struct PlanExecutor<'a> {
    pub registry: &'a ToolRegistry,
    pub policy: &'a PolicyEngine,
}

impl<'a> PlanExecutor<'a> {
    /// Runs as many steps as it safely can. Returns a report the caller
    /// (Tauri command layer) uses to decide what to tell the user and
    /// whether a HIGH_RISK confirmation needs to be surfaced before
    /// resuming from the current step.
    ///
    /// `plan_id` is generated by the caller (see `commands.rs`) BEFORE
    /// execution starts, so a cancellation request racing in from the UI
    /// has a valid id to target from the first moment the plan exists.
    pub fn run(&self, plan_id: &str, steps: &[PlanStep], token: &CancellationToken) -> PlanReport {
        let mut outcomes = Vec::new();
        let mut completed = 0;
        let mut stopped_early = false;

        for step in steps {
            if token.is_cancelled() {
                outcomes.push(PlanStepOutcome::Cancelled);
                stopped_early = true;
                break;
            }

            let Some(tool) = self.registry.get(&step.tool_id) else {
                outcomes.push(PlanStepOutcome::Failed { error: format!("unknown tool '{}'", step.tool_id) });
                stopped_early = true;
                break;
            };

            if let Err(e) = tool.validate(&step.params) {
                outcomes.push(PlanStepOutcome::Failed { error: e.to_string() });
                stopped_early = true;
                break;
            }

            let effect = tool.describe_effect(&step.params);
            let decision = self.policy.evaluate(&step.tool_id, tool.risk_level(), tool.name(), &step.params.to_string(), &effect);

            match decision {
                PolicyDecision::Deny { reason } => {
                    outcomes.push(PlanStepOutcome::Failed { error: reason });
                    stopped_early = true;
                    break;
                }
                PolicyDecision::RequireConfirmation { explanation } => {
                    // Stop here. The plan is resumable from this step once
                    // the frontend collects CONFIRM/CANCEL — the planner
                    // never assumes consent.
                    outcomes.push(PlanStepOutcome::NeedsConfirmation { explanation });
                    stopped_early = true;
                    break;
                }
                PolicyDecision::Allow => match tool.execute(&step.params) {
                    Ok(ToolResult { conflict: Some(c), .. }) => {
                        outcomes.push(PlanStepOutcome::Conflict { reason: c.reason, destination: c.destination });
                        stopped_early = true;
                        break;
                    }
                    Ok(result) => {
                        outcomes.push(PlanStepOutcome::Success { message: result.message, data: result.data });
                        completed += 1;
                    }
                    Err(e) => {
                        outcomes.push(PlanStepOutcome::Failed { error: e.to_string() });
                        stopped_early = true;
                        break;
                    }
                },
            }
        }

        let summary = if stopped_early {
            format!("{completed} of {} steps completed.", steps.len())
        } else {
            format!("All {completed} steps completed.")
        };

        PlanReport {
            plan_id: plan_id.to_string(),
            total_steps: steps.len(),
            completed_steps: completed,
            outcomes,
            stopped_early,
            summary,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::actions::ToolRegistry;
    use crate::security::PolicyEngine;

    #[test]
    fn stops_at_first_confirmation_required_step_without_executing_it() {
        let registry = ToolRegistry::new();
        let policy = PolicyEngine::new();
        let executor = PlanExecutor { registry: &registry, policy: &policy };
        let token = CancellationToken::new();

        let steps = vec![
            PlanStep {
                tool_id: "open_url".into(),
                params: serde_json::json!({ "url": "https://example.com" }),
                description: "open example.com".into(),
            },
            // open_application is currently LOW_RISK in this registry, so
            // this test documents behavior for whichever step is the first
            // HIGH_RISK+ one once such a tool is registered; for now it
            // verifies safe steps execute and report completion accurately.
        ];

        let report = executor.run("test-plan", &steps, &token);
        assert_eq!(report.completed_steps, 1);
        assert!(!report.stopped_early);
    }

    #[test]
    fn cancellation_stops_remaining_steps_and_reports_accurately() {
        let registry = ToolRegistry::new();
        let policy = PolicyEngine::new();
        let executor = PlanExecutor { registry: &registry, policy: &policy };
        let token = CancellationToken::new();
        token.cancel(); // simulate cancel arriving before the plan starts

        let steps = vec![PlanStep {
            tool_id: "open_url".into(),
            params: serde_json::json!({ "url": "https://example.com" }),
            description: "open example.com".into(),
        }];

        let report = executor.run("test-plan", &steps, &token);
        assert_eq!(report.completed_steps, 0);
        assert!(report.stopped_early);
        assert!(matches!(report.outcomes[0], PlanStepOutcome::Cancelled));
    }

    #[test]
    fn unknown_tool_in_plan_fails_closed_not_open() {
        let registry = ToolRegistry::new();
        let policy = PolicyEngine::new();
        let executor = PlanExecutor { registry: &registry, policy: &policy };
        let token = CancellationToken::new();

        let steps = vec![PlanStep {
            tool_id: "delete_c_drive".into(),
            params: serde_json::json!({}),
            description: "malicious".into(),
        }];

        let report = executor.run("test-plan", &steps, &token);
        assert_eq!(report.completed_steps, 0);
        assert!(matches!(report.outcomes[0], PlanStepOutcome::Failed { .. }));
    }
}
